version: '3'
services: 
  app: 
    build: 
      context: .
      dockerfile: ./Dockerfiles/Python/Dockerfile
    tty: true
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume: