# Generated by Django 3.1.5 on 2021-07-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benevolence_factor', models.PositiveSmallIntegerField(default=50, help_text='How benevolent this hero is?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample5.category')),
            ],
        ),
    ]
