# Generated by Django 3.1.5 on 2021-06-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_user_id',
        ),
    ]
