# Generated by Django 3.1.5 on 2021-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample4', '0002_auto_20210701_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ユーザ', max_length=255),
            preserve_default=False,
        ),
    ]
