# Generated by Django 3.1.5 on 2021-01-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
