# Generated by Django 3.1.5 on 2021-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='市', max_length=255),
            preserve_default=False,
        ),
    ]
